server:
  port:8080

#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: employeeModule
#            uri: http://localhost:8010/
#            predicates:
#              - Path=/employee/**
#          - id: consumerModule
#            uri: http://localhost:8020/
#            predicates:
#              - Path=/consumer/**

service:
  first:
    uri: http://localhost:8010/
  second:
    uri: http://localhost:8020