spring:
  application:
    name: first-service
server:
  port: 8010

resilience4j.circuitbreaker:
  instances:
    backendA:
      registerHealthIndicator: true
      slidingWindowSize: 100
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - java.lang.Exception
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
      ignoreExceptions:
        - java.lang.IllegalArgumentException

resilience4j:
  timelimiter:
    instances:
      backendA:
        timeoutDuration: 5s
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: resilience4j
